apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
  namespace: capstone
  labels:
    app: customer
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: customer
          image: 395312722260.dkr.ecr.us-west-2.amazonaws.com/spring-api:latest
          ports:
            - containerPort: 8080
